### ISSUE TITLE
LOW - periodo de tiempo del juego en la pantalla

### ISSUE THREAD

**Issue by etoya85** [jimbomilk/addmeetooMng#12]
_mira los comentarios tb_

no sé si los juegos tienen que permanecer en la pantalla durante el mismo periodo de tiempo o no. aquí te adjunto una tabla que muestra en que segundo de cada marcha se cambian. es evidente que algunas actividades permanecen dos o tres vecez más en la pantalla que las otras. Puede ser lógico, dado que eurovision, por ejemplo, tiene más opciones. pero en todos casos echa un vistazo.
![marchas](https://user-images.githubusercontent.com/30647934/28918998-d6b65ac0-784b-11e7-9f3c-6c1d440fccbf.JPG)

**Comment by etoya85** [comment]
UPDATE: he parado el juego Eurovision, ahora en cambio de eurovision hay partido de fútbol, que dura el mismo periodo de tiempo como eurovision. Entonces - no tiene nada que ver con el número de opciones.

**Comment by jimbomilk** [comment]
Done
