### ISSUE TITLE
LOW - boton preview

### ISSUE THREAD

**Issue by etoya85** [jimbomilk/addmeetooMng#13]
pulsando el boton preview a vecez hace el juego aparecer en la pantalla entre otras actividades por un segundo o dos, luego desaparece y no aparece hasta que pulsemos **_En marcha_**. Está bien, solo que todavia no entiendo para que sirve el boton. a lo mejor hagamos vista previa con el o lo borramos totalmente?
_**pensemoslo bien antes de hacer algo y mientras - no lo usemos.**_

**Comment by jimbomilk** [comment]
Si ya no tiene ninguna función, lo podemos dejar para nosotros porque nos permite que veamos inmediatamente los cambios...lo cual es muy positivo para testing...pero deberiamos ocultarlo para el resto de perfiles
