### ISSUE TITLE
MEDIUM - number of options to introduce

### ISSUE THREAD

**Issue by etoya85** [jimbomilk/addmeetooMng#16]
we need to limit in the system technical possibility to introduce more than XX options of the game. I suggest to limit it by 8. In case of Eurovision we managed to put 10, but when I enter 15 of La Vuelta the screen shows only 8.

**Comment by jimbomilk** [comment]
Yes fully agree...updated to maximum 10!

**Comment by jimbomilk** [comment]
to review

**Comment by etoya85** [comment]
let´s limit with 8. I dont know why but for example with la vuelta de españa the screen only shows 8 options, although i introduce ten.
