### ISSUE TITLE
MEDIUM - finalización del juego antes del tiempo programado

### ISSUE THREAD

**Issue by etoya85** [jimbomilk/addmeetooMng#17]
para finalizar el juego **antes** de su tiempo hay que entrar en el y cambiar la fecha y la hora de su finalización. Sería más cómodo solo darle a **_finalizado_** sin tener que entrar y cambiar las fechas. Por el momento no se puede - aunque lo doy **_finalizado_** después del rato se vuelve a **_en marcha_** automaticamente.

**Comment by jimbomilk** [comment]
Done
