### ISSUE TITLE
MEDIUM - introducción de fechas

### ISSUE THREAD

**Issue by etoya85** [jimbomilk/addmeetooMng#8]
**primero lee lo todo, por favor**

el sistema muestra un error
_

> Please fix the errors:
> El valor de endgame debe ser una fecha posterior a startgame.
> El valor de startgame debe ser una fecha anterior a endgame.

_
está bien, PERO - ambas errores significan lo mismo, dejemos solo una

pero hay otro fallo - el sistema me deja entrar la fecha **_Participacion hasta_** que precede a la fecha **_Inicio de juego_**

i will sum up to make it easier for you:
1. **_Participacion hasta_** cannot have the date which is earlier than the date of **_Inicio juego_**. If so, there shall appear this error: _El valor Participación hasta debe ser una fecha posterior a Inicio juego_.
2. **_Fin juego_** cannot have the date which is earlier than the date of **_Inicio juego_**. If so, there shall appear this error: _El valor Fin juego debe ser una fecha posterior a Inicio juego_.
3. **_Fin juego_** cannot have the date which is earlier than the date of **_Participación hasta_**. If so, there shall appear this error: _El valor Fin juego debe ser una fecha posterior o igual (igual se puede??) a Participación hasta_. Técnicamente la fecha no puede ser igual ahora, pero creo que si, porque no?

p.s: por favor, introduce todo en Addmeetoo en el misma idioma, no podemos mezclar dos idiomas. Hacemos el programa para los españoles, entonces todo tiene que ser en español.

**Comment by jimbomilk** [comment]
Hecho aunque los nombres de los campos no pueden estar en español :(
